name = "AquaCrop"
uuid = "8f16cebd-c0b4-44a3-857f-c101f083256c"
authors = ["Gabriel Diaz <gabriel.diaz.iturry@gmail.com>"]
version = "0.0.1-DEV"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
ComponentArrays = "0.15"
Infiltrator = "1"
TOML = "1"
julia = "1.9"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
