name = "AquaCrop"
uuid = "8f16cebd-c0b4-44a3-857f-c101f083256c"
authors = ["Gabriel Diaz <gabriel.diaz.iturry@gmail.com>"]
version = "0.0.1-DEV"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"

[compat]
ComponentArrays = "0.15"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[targets]
test = ["Test", "SafeTestsets"]
