UHK (Germany)
      7.1       : AquaCrop Version (August 2023)
      1         : Year number of cultivation (Seeding/planting year)
  41750         : First day of simulation period - 22 April 2015      
  42299         : Last day of simulation period - 22 October 2016  
  41757         : First day of cropping period - 29 April 2014      
  42158         : Last day of cropping period - 03 June 2016  
-- 1. Climate (CLI) file
   uhk.CLI
   './DATA/'
   1.1 Temperature (Tnx or TMP) file
   uhk.Tnx
   './DATA/'
   1.2 Reference ET (ETo) file
   uhk.ETo
   './DATA/'
   1.3 Rain (PLU) file
   uhk.PLU
   './DATA/'
   1.4 Atmospheric CO2 concentration (CO2) file
   MaunaLoa.CO2
   './SIMUL/'
-- 2. Calendar (CAL) file
   (None) 
   (None) 
-- 3. Crop (CRO) file
   MaizeGDD.CRO
   './DATA/'
-- 4. Irrigation management (IRR) file
   (None)
   (None)
-- 5. Field management (MAN) file
   (None) 
   (None) 
-- 6. Soil profile (SOL) file
   Loam.SOL
   './DATA/'
-- 7. Groundwater table (GWT) file
   (None)
   (None)
-- 8. Initial conditions (SW0) file
   (None)
   (None)
-- 9. Off-season conditions (OFF) file
   (None)
   (None)
-- 10. Field data (OBS) file
   (None) 
   (None) 
