UHK (Germany)
      7.1       : AquaCrop Version (August 2023)
      1         : Year number of cultivation (Seeding/planting year)
  43736         : First day of simulation period - 28 September 2020     
  44282         : Last day of simulation period - 28 March 2022 
  43743         : First day of cropping period - 05 October 2020      
  43976         : Last day of cropping period - 26 May 2021  
-- 1. Climate (CLI) file
   uhk.CLI
   './DATA/'
   1.1 Temperature (Tnx or TMP) file
   uhk.Tnx
   './DATA/'
   1.2 Reference ET (ETo) file
   uhk.ETo
   './DATA/'
   1.3 Rain (PLU) file
   uhk.PLU
   './DATA/'
   1.4 Atmospheric CO2 concentration (CO2) file
   MaunaLoa.CO2
   './SIMUL/'
-- 2. Calendar (CAL) file
   (None) 
   (None) 
-- 3. Crop (CRO) file
   BarleyGDD.CRO
   './DATA/'
-- 4. Irrigation management (IRR) file
   (None)
   (None)
-- 5. Field management (MAN) file
   (None) 
   (None) 
-- 6. Soil profile (SOL) file
   Loam.SOL
   './DATA/'
-- 7. Groundwater table (GWT) file
   (None)
   (None)
-- 8. Initial conditions (SW0) file
   (None)
   (None)
-- 9. Off-season conditions (OFF) file
   (None)
   (None)
-- 10. Field data (OBS) file
   (None) 
   (None) 
